In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("pcos_data.csv")

In [4]:
df.head()

,Timestamp,Have you been diagnosed(tested) with PCOS ?,You had/have PCOS ?,Select your age at which you had PCOS,Were you overweight according to your BMI (Body Mass Index) ?,Have you experienced significant or rapid weight gain and faced difficulty in losing it ?,Have you experienced irregular or missed periods ?,Difficulty in conceiving ?,Chin,Cheeks,...,Inner thighs,Acne or skin tags problem ?,Hair thinning or hair loss problems ?,Dark patches on the back of your neck or underarms ?,Feeling of tiredness all the time ?,Mood Swings more often than usual ?,How many days in a week did you exercise ?,How many times a week did you eat outside ?,Did you consume canned food more often ?,Did you move to a different city/location before experiencing the above conditions ?
0,2018/09/07 3:09:04 PM GMT+5:30,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018/09/07 3:11:16 PM GMT+5:30,Yes,No,23.0,NO,NaN,No,No,3.0,4.0,...,3.0,No,No,No,Yes,Yes,3.0,4.0,Yes,No
2,2018/09/09 8:58:58 PM GMT+5:30,Yes,Yes,22.0,YES,No,No,No,4.0,1.0,...,1.0,Yes,Yes,No,Yes,Yes,4.0,3.0,No,No
3,2018/09/12 8:29:28 AM GMT+5:30,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018/09/12 8:30:01 AM GMT+5:30,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['Timestamp', 'Have you been diagnosed(tested) with PCOS  ?',
       'You had/have  PCOS ?', 'Select your age at which you had PCOS',
       'Were you overweight according to your BMI (Body Mass Index) ?',
       'Have you experienced significant or rapid weight gain and faced difficulty in losing it ?',
       'Have you experienced irregular or missed periods ?',
       'Difficulty in conceiving ?', 'Chin', 'Cheeks', 'Upper Lips',
       'Between breast', 'Arms', 'Inner thighs', 'Acne or skin tags problem ?',
       'Hair thinning or hair loss problems ?',
       'Dark patches on the back of your neck or underarms ?',
       'Feeling of  tiredness all the time ?',
       'Mood Swings more often than usual ?',
       'How many days in a week did you exercise ?',
       'How many times a week did you eat outside  ?',
       'Did you consume canned food more often ?',
       'Did you move to a different city/location before experiencing the above conditions ?'],
      dtype='object')

In [6]:
df.columns=['time','diagnosed','result','age','overweight','weightgain','periods','conceiving','chinHair','cheeksHair','upperLipHair','betweenBreastHair','armsHair','innerThighHair','acneOrskinTag','hairThinning','darkPatch','tiredness','moodSwings','exercise','eatOutside','cannedFood','city']

In [7]:
df.head()

,time,diagnosed,result,age,overweight,weightgain,periods,conceiving,chinHair,cheeksHair,...,innerThighHair,acneOrskinTag,hairThinning,darkPatch,tiredness,moodSwings,exercise,eatOutside,cannedFood,city
0,2018/09/07 3:09:04 PM GMT+5:30,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018/09/07 3:11:16 PM GMT+5:30,Yes,No,23.0,NO,NaN,No,No,3.0,4.0,...,3.0,No,No,No,Yes,Yes,3.0,4.0,Yes,No
2,2018/09/09 8:58:58 PM GMT+5:30,Yes,Yes,22.0,YES,No,No,No,4.0,1.0,...,1.0,Yes,Yes,No,Yes,Yes,4.0,3.0,No,No
3,2018/09/12 8:29:28 AM GMT+5:30,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018/09/12 8:30:01 AM GMT+5:30,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df['diagnosed'].describe

<bound method NDFrame.describe of 0       No
1      Yes
2      Yes
3       No
4       No
      ...
287    Yes
288    Yes
289    Yes
290    Yes
291    Yes
Name: diagnosed, Length: 292, dtype: object>

In [9]:
set(df['result'])

{'No', 'No(Detected Negative)', 'Yes', 'Yes(Detected Positive)', nan}

In [10]:
df.drop(labels = ["time"] ,axis = 1 , inplace = True  )

In [11]:
final =pd.DataFrame(df[df.diagnosed=='Yes'])

In [12]:
final.columns

Index(['diagnosed', 'result', 'age', 'overweight', 'weightgain', 'periods',
       'conceiving', 'chinHair', 'cheeksHair', 'upperLipHair',
       'betweenBreastHair', 'armsHair', 'innerThighHair', 'acneOrskinTag',
       'hairThinning', 'darkPatch', 'tiredness', 'moodSwings', 'exercise',
       'eatOutside', 'cannedFood', 'city'],
      dtype='object')

In [13]:
y = final[['result']]

In [14]:
y.head()

  result
1     No
2    Yes
6    Yes
7    Yes
8    Yes

In [16]:
final.drop(labels = ["result"] ,axis = 1 , inplace = True )

In [17]:
final.head()

,diagnosed,age,overweight,weightgain,periods,conceiving,chinHair,cheeksHair,upperLipHair,betweenBreastHair,...,innerThighHair,acneOrskinTag,hairThinning,darkPatch,tiredness,moodSwings,exercise,eatOutside,cannedFood,city
1,Yes,23.0,NO,NaN,No,No,3.0,4.0,4.0,3.0,...,3.0,No,No,No,Yes,Yes,3.0,4.0,Yes,No
2,Yes,22.0,YES,No,No,No,4.0,1.0,3.0,2.0,...,1.0,Yes,Yes,No,Yes,Yes,4.0,3.0,No,No
6,Yes,26.0,NO,NaN,No,No,1.0,1.0,1.0,1.0,...,1.0,No,Yes,No,No,Yes,1.0,6.0,No,No
7,Yes,20.0,YES,Yes,Yes,No,3.0,2.0,4.0,3.0,...,3.0,No,No,Yes,Yes,Yes,5.0,2.0,No,Yes
8,Yes,19.0,NO,NaN,Yes,No,3.0,1.0,4.0,3.0,...,3.0,Yes,Yes,No,Yes,Yes,2.0,2.0,Yes,No

In [18]:
 from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
def encoder(s):
# label_encoder object 
    final[s]= label_encoder.fit_transform(final[s].astype(str)) 
    final[s].unique()

In [19]:
categorical_columns = final.select_dtypes(exclude=['int64', 'float64']).columns.values      
for column in categorical_columns:
        encoder(column)
final.head()

,diagnosed,age,overweight,weightgain,periods,conceiving,chinHair,cheeksHair,upperLipHair,betweenBreastHair,...,innerThighHair,acneOrskinTag,hairThinning,darkPatch,tiredness,moodSwings,exercise,eatOutside,cannedFood,city
1,0,23.0,0,2,0,0,3.0,4.0,4.0,3.0,...,3.0,0,0,0,1,1,3.0,4.0,1,0
2,0,22.0,2,0,0,0,4.0,1.0,3.0,2.0,...,1.0,1,1,0,1,1,4.0,3.0,0,0
6,0,26.0,0,2,0,0,1.0,1.0,1.0,1.0,...,1.0,0,1,0,0,1,1.0,6.0,0,0
7,0,20.0,2,1,1,0,3.0,2.0,4.0,3.0,...,3.0,0,0,1,1,1,5.0,2.0,0,1
8,0,19.0,0,2,1,0,3.0,1.0,4.0,3.0,...,3.0,1,1,0,1,1,2.0,2.0,1,0

In [20]:
final.dtypes

diagnosed              int32
age                  float64
overweight             int32
weightgain             int32
periods                int32
conceiving             int32
chinHair             float64
cheeksHair           float64
upperLipHair         float64
betweenBreastHair    float64
armsHair             float64
innerThighHair       float64
acneOrskinTag          int32
hairThinning           int32
darkPatch              int32
tiredness              int32
moodSwings             int32
exercise             float64
eatOutside           float64
cannedFood             int32
city                   int32
dtype: object

In [23]:
def f(s):
    if(s=="Yes"):
        return True
    if(s=="No"):
        return False
    if(s=="Yes(Detected Positive)"):
        return True
    if(s=="No(Detected Negative)"):
        return False
y=y.result.apply(f)

y.head()

1    False
2     True
6     True
7     True
8     True
Name: result, dtype: bool

In [24]:
xnew=final.values
ynew=y.values

In [25]:
xnew

array([[ 0., 23.,  0., ...,  4.,  1.,  0.],
       [ 0., 22.,  2., ...,  3.,  0.,  0.],
       [ 0., 26.,  0., ...,  6.,  0.,  0.],
       ...,
       [ 0., 19.,  1., ...,  5.,  0.,  0.],
       [ 0., 25.,  3., ...,  1.,  1.,  1.],
       [ 0., 26.,  1., ...,  1.,  0.,  0.]])

In [26]:

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(copy=True)
scaler.fit(xnew)
x_scaled=scaler.transform(xnew)

In [27]:
x_scaled

array([[0.        , 0.3125    , 0.        , ..., 0.27272727, 1.        ,
        0.        ],
       [0.        , 0.28125   , 0.66666667, ..., 0.18181818, 0.        ,
        0.        ],
       [0.        , 0.40625   , 0.        , ..., 0.45454545, 0.        ,
        0.        ],
       ...,
       [0.        , 0.1875    , 0.33333333, ..., 0.36363636, 0.        ,
        0.        ],
       [0.        , 0.375     , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.40625   , 0.33333333, ..., 0.        , 0.        ,
        0.        ]])

In [28]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(xnew,ynew,random_state=3)

In [29]:
from numpy import savetxt
savetxt('x_train.csv', x_train, delimiter=',')
savetxt('y_train.csv', y_train, delimiter=',')
savetxt('x_test.csv', x_test, delimiter=',')
savetxt('y_test.csv', y_test, delimiter=',')

In [244]:
x_train.to_csv( "X_Train_Dataset.csv")
y_train.to_csv( "Y_Train_Dataset.csv")
x_test.to_csv(  "X_Test_Dataset.csv")
y_test.to_csv( "Y_Test_Dataset.csv")

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

In [34]:
xnew.shape
y.shape[1]

IndexError: tuple index out of range

In [156]:
from sklearn.metrics import classification_report,confusion_matrix

In [185]:
from sklearn.svm import SVC
clf=SVC(kernel='poly',degree=2,C=0.01)
clf.fit(x_train,y_train)
ypredsvm=clf.predict(x_test)
clf.score(x_train,y_train),clf.score(x_test,y_test)
print('svc Accuracy Score:',round(accuracy_score(y_test,ypredsvm)*100),'%')

svc Accuracy Score: 63.0 %

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [228]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
clf1=DecisionTreeClassifier()
clf1.fit(x_train,y_train)
ypredDT=clf1.predict(x_test)
clf1.score(x_train,y_train),clf1.score(x_test,y_test)
print('Decision Accuracy Score:',round(accuracy_score(y_test,ypredDT)*100),'%')

Decision Accuracy Score: 68.0 %

In [226]:
Random_forest_model = RandomForestClassifier(class_weight='balanced')
Random_forest_model.fit(x_train,y_train.ravel())
prediction_Random_forest_model = Random_forest_model.predict(x_test)
print('Random Forest Accuracy Score:',round(accuracy_score(y_test.ravel(),prediction_Random_forest_model)*100),'%')

Random Forest Accuracy Score: 78.0 %

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [238]:
from sklearn.linear_model import LogisticRegression
clf3 = LogisticRegression(C=0.01)
clf3.fit(x_train,y_train)
ypredLR=clf3.predict(x_test)
clf3.score(x_train,y_train),clf3.score(x_test,y_test)
print('LR Accuracy Score:',round(accuracy_score(y_test,ypredLR)*100),'%')

knn Accuracy Score: 63.0 %

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [235]:

from sklearn.neighbors import KNeighborsClassifier
clf6=KNeighborsClassifier(n_neighbors=3)
clf6.fit(x_train,y_train)
ypredKNN=clf6.predict(x_test)
clf6.score(x_train,y_train),clf6.score(x_test,y_test)
print('knn Accuracy Score:',round(accuracy_score(y_test,ypredKNN)*100),'%')

knn Accuracy Score: 66.0 %

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

In [245]:
x_train1 = pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.0,26.0,1.0,2.0,0.0,0.0,4.0,4.0,4.0,1.0,...,2.0,1.0,1.0,0.0,1.0,1.0,5.0,1.0,0.0,0.0
1,0.0,20.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,3.0,0.0,0.0
2,0.0,23.0,3.0,0.0,0.0,1.0,2.0,1.0,3.0,1.0,...,3.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0
3,0.0,20.0,3.0,1.0,1.0,1.0,4.0,5.0,4.0,4.0,...,3.0,0.0,1.0,1.0,0.0,1.0,5.0,2.0,0.0,0.0
4,0.0,18.0,2.0,1.0,1.0,0.0,3.0,1.0,2.0,2.0,...,2.0,1.0,1.0,1.0,1.0,1.0,2.0,5.0,0.0,1.0